### ISSUE TITLE
Nuget package is not the latest code

### ISSUE THREAD

**Issue by mumair85** [RobThree/SimpleFeedReader#10]
Not an actual issue, but the nuget package v1.0.7 does not have not the latest code as in this repository. I did check your latest commit was on 9th March 2017 and same day published to nuget, but the class `FeedItem` on nuget does not have property `Images` (and there might be other differences as well).

Can you update nuget?

**Comment by RobThree** [comment]
Hmmm, not quite sure what happened there. Should be solved [with 1.0.8](https://www.nuget.org/packages/SimpleFeedReader/1.0.8).

**Comment by mumair85** [comment]
Thanks, that fixed it.
