### ISSUE TITLE
How to limit to just latest item?

### ISSUE THREAD

**Issue by iamjudd** [RobThree/SimpleFeedReader#8]
I am implementing this into a discord bot and I'd like to grab only the latest item from an rss feed.
How would I do this?

**Comment by RobThree** [comment]
var reader = new FeedReader();
    var latest = reader.RetrieveFeed("http://domain.com/feed.rss")
                       .OrderByDescending(i => i.Date)
                       .FirstOrDefault();

Something like this I guess? `RetrieveFeed()` returns an `IEnumerable<FeedItem>` and from there on it's simply a matter of using [Linq](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/) to filter/order/group/transform etc. the items however you want.
