### ISSUE TITLE
Package not registering

### ISSUE THREAD

**Issue by Neo5Xo** [RobThree/SimpleFeedReader#9]
![screen shot 2017-10-01 at 4 39 17 pm](https://user-images.githubusercontent.com/6758443/31058770-20f799a6-a6c7-11e7-896e-b8eff5c1b803.png)
Xamarin is not registering SimpleFeedReader.  Is there any way this can be fixed?

**Comment by Dids** [comment]
Seeing the same thing here. It's probably not strictly Xamarin-related, but more likely something wrong with the NuGet package itself.

**Comment by Dids** [comment]
Figured out a workaround.

The issue is that the package (the DLL) isn't getting referenced automatically, which it definitely should.

You can manually edit references, then browser to packages/SimpleReader and select the DLL, after which it should start working again.

**Comment by RobThree** [comment]
I’m currently not in a position to fix this (hospitalized; nothing too bad though). Will have a look at this as soon as I can. PR’s are welcome.

**Comment by RobThree** [comment]
Sorry didn’t mean to close... 😬

**Comment by Dids** [comment]
Update: simply adding a reference manually isn't enough, as it looks like it's still not getting included in the compiled app:

```
Could not load type of field 'SimpleFeedReader.DefaultFeedItemNormalizer:CS$<>9__CachedAnonymousMethodDelegate2' (3) due to: Could not resolve type with token 01000019 (from typeref, class/assembly System.ServiceModel.Syndication.SyndicationLink, System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089) assembly:System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:System.ServiceModel.Syndication.SyndicationLink member:<none>
```

**Comment by Dids** [comment]
@RobThree No worries, get better soon! I'll see if I can whip up a quick PR in the mean time.

**Comment by Dids** [comment]
Not sure I have the time, unfortunately, as this would most likely need to be migrated to .NET Standard (2.0), which would also mean switching to the new .NET Standard compatible syndication feed reader/write, available here: https://github.com/dotnet/SyndicationFeedReaderWriter

**Comment by RobThree** [comment]
See #11
